### ISSUE TITLE
 An error encountered while running Demo

### ISSUE THREAD

**Issue by elecCore** [kayako/KayakoMessengeriOS#8]
Demo encountered an error when running "Carthage update --platform iOS":
Log error information:
[
![2ae974e7-73cc-4805-86a2-7db51053c79f](https://user-images.githubusercontent.com/8007151/30904000-3299fb0c-a336-11e7-9342-fae9d9e0ff2c.png)
](url)

[carthage-xcodebuild.0EDS0n.log](https://github.com/kayako/KayakoMessengeriOS/files/1336347/carthage-xcodebuild.0EDS0n.log)

To test, I integrate Kayako into the Objective-C project in framewrok form via Cocoapods.
After I click "satart a new conversation", crash in 'Texture' Assert，as detailed below:

![9cdf39a9-d0c3-439a-af20-5f28193e070f](https://user-images.githubusercontent.com/8007151/30904050-5f47021c-a336-11e7-8eae-e56d2c9411c4.png)

**Comment by codeOfRobin** [comment]
Interesting.

For the first error, I'll look into why Starscream seems to not compile (probably just needs a newer version)

As for the second, could you send me your stacktrace?

**Comment by elecCore** [comment]
Look at this Demo.
git@github.com:elecCore/testKayako.git

 In addition, there is a compile error. I made a simple adjustment. The code changes the drawings:

![6965df7d-8416-415d-a37f-e461ab05b32e](https://user-images.githubusercontent.com/8007151/30945183-59af5b74-a3c2-11e7-83a1-ba3207a8aa24.png)

![7f12748b-8e97-43d8-a02c-598f7ac0d5fb](https://user-images.githubusercontent.com/8007151/30945187-627b15fe-a3c2-11e7-9153-c1ca11a3aaa5.png)

**Comment by codeOfRobin** [comment]
Awesome! Thank you so much for providing the stacktrace. I'll start looking at the bug as soon as possible

**Comment by codeOfRobin** [comment]
Hey! I think I've fixed the issue with #5 . Could you pull the latest pod (v0.2.2) or carthage update ?

**Comment by elecCore** [comment]
I updated the 0.2.2 version of kayako in demo, but it didn't solve the problem...

[https://github.com/elecCore/testKayako](url)

**Comment by codeOfRobin** [comment]
Hey! Thank you so much for that repo! I've managed to narrow down the bug and pushed a fix (0.2.3). I've also forked your test repo so you can check out the fixes yourself: https://github.com/codeOfRobin/testKayako

**Comment by codeOfRobin** [comment]
Hey! It's been reported this issue is fixed #9 , so I'm closing for now. Feel free to re-open if you encounter it again
